### ISSUE TITLE
Help documentation waits for a network timeout before displaying when offline.

### ISSUE THREAD

**Issue by mikebolt** [git-for-windows/git#803]
When using the offline help documentation, and typing e.g. `git pull --help`, the help page takes over 20 seconds to display, which can be frustrating. It waits for a font from fonts.googleapis.com. Could this font simply be included in the project so that it doesn't require an internet connection? If not, it still should not wait for the font to load before displaying when offline.

Also, I would like to thank the maintainers of this project. I have had a great experience with git for Windows so far, and I use it as my main shell whenever I work on Windows.

**Comment by dscho** [comment]
> Could this font simply be included in the project so that it doesn't require an internet connection?

I don't know... Could it?

**Comment by dscho** [comment]
A quick web search comes up with this link: http://stackoverflow.com/questions/15930003/downloading-a-google-font-and-setting-up-an-offline-site-that-uses-it

If purports that you just have to replace the link "https://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic%7CNoto+Serif:400,400italic,700,700italic%7CDroid+Sans+Mono:400,700" with the contents of the downloaded file.

However, there is no mention of this URL in Git's source code!

So I will ask for your time and effort, now, @mikebolt. Can you generate the html help and find out where that link enters the game? I have way too much on my plate to invest more in this project than the half hour I already did.

**Comment by mikebolt** [comment]
Alright, I'm looking into it. It has something to do with the asciidoc theme.

**Comment by dscho** [comment]
> Alright, I'm looking into it.

Thanks!

> It has something to do with the asciidoc theme.

Right. We actually use asciidoctor because it is significantly faster in MSYS2. A quick search brings up the following:

```sh
$ grep -l fonts.googleapis.com $(find /mingw64/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/ -type f)
/mingw64/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/data/stylesheets/asciidoctor-default.css
/mingw64/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/converter/html5.rb
/mingw64/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/document_test.rb
```

Obviously, I do not plan to fix asciidoctor. But maybe we can play some post-processing games while [building the `mingw-w64-git-doc-html` package](https://github.com/git-for-windows/git/wiki/Package-management#rebuild-packages)?

We would need to patch [`/usr/src/MINGW-packages/mingw-w64-git/PKGBUILD`](https://github.com/git-for-windows/MINGW-packages/blob/master/mingw-w64-git/PKGBUILD), probably during the [`package_git-doc-html` function](https://github.com/git-for-windows/MINGW-packages/blob/e38cca77c3fcba2429729ecbb90ea10080893f54/mingw-w64-git/PKGBUILD#L185-L192).

Maybe something along the lines of

```sh
urls="$(grep "$pkgdir" fonts.googleapis.com $(find -name \*.html) |
    sed -n 's|.*"\(https://fonts.googleapis.com[^"]*\).*|\1|p' |
    sort |
    uniq)"
# now fetch those URLs, copy the output into local files, and then replace the URLs with local ones
```

**Comment by mikebolt** [comment]
I consider this an issue with asciidoctor, and so does one of the asciidoctor maintainers: https://github.com/asciidoctor/asciidoctor/issues/1244. I think string replacement is a good workaround until that gets fixed.

**Comment by mikebolt** [comment]
Apparently that CSS font file just references 71 different font urls from fonts.gstatic.com, so there's 72 required files and some considerable regex magic required.

**Comment by mikebolt** [comment]
We could just remove the line containing the font stylesheet link element in each html file. It wouldn't use the nice font but it's a much easier solution. Something like this:

    for htmlDocFile in *.html do
        grep -vh "fonts\.googleapis\.com/css" "$htmlDocFile" > "$htmlDocFile"
    done

**Comment by dscho** [comment]
When I use `curl "https://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic%7CNoto+Serif:400,400italic,700,700italic%7CDroid+Sans+Mono:400,700"` to download the `.css` file, I get this:

```css
@font-face {
  font-family: 'Droid Sans Mono';
  font-style: normal;
  font-weight: 400;
  src: local('Droid Sans Mono'), local('DroidSansMono'), url(https://fonts.gstatic.com/s/droidsansmono/v7/ns-m2xQYezAtqh7ai59hJYW_AySPyikQrZReizgrnuw.ttf) format('truetype');
}
@font-face {
  font-family: 'Noto Serif';
  font-style: normal;
  font-weight: 400;
  src: local('Noto Serif'), local('NotoSerif'), url(https://fonts.gstatic.com/s/notoserif/v4/eCpfeMZI7q4jLksXVRWPQy3USBnSvpkopQaUR-2r7iU.ttf) format('truetype');
}
@font-face {
  font-family: 'Noto Serif';
  font-style: normal;
  font-weight: 700;
  src: local('Noto Serif Bold'), local('NotoSerif-Bold'), url(https://fonts.gstatic.com/s/notoserif/v4/lJAvZoKA5NttpPc9yc6lPfEr6Hm6RMS0v1dtXsGir4g.ttf) format('truetype');
}
@font-face {
  font-family: 'Noto Serif';
  font-style: italic;
  font-weight: 400;
  src: local('Noto Serif Italic'), local('NotoSerif-Italic'), url(https://fonts.gstatic.com/s/notoserif/v4/HQXBIwLHsOJCNEQeX9kNz4nF5uFdDttMLvmWuJdhhgs.ttf) format('truetype');
}
@font-face {
  font-family: 'Noto Serif';
  font-style: italic;
  font-weight: 700;
  src: local('Noto Serif Bold Italic'), local('NotoSerif-BoldItalic'), url(https://fonts.gstatic.com/s/notoserif/v4/Wreg0Be4tcFGM2t6VWytvH06qf9KHRHwsVx7iw5MXmY.ttf) format('truetype');
}
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 300;
  src: local('Open Sans Light'), local('OpenSans-Light'), url(https://fonts.gstatic.com/s/opensans/v13/DXI1ORHCpsQm3Vp6mXoaTYnF5uFdDttMLvmWuJdhhgs.ttf) format('truetype');
}
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 400;
  src: local('Open Sans'), local('OpenSans'), url(https://fonts.gstatic.com/s/opensans/v13/cJZKeOuBrn4kERxqtaUH3aCWcynf_cDxXwCLxiixG1c.ttf) format('truetype');
}
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 600;
  src: local('Open Sans Semibold'), local('OpenSans-Semibold'), url(https://fonts.gstatic.com/s/opensans/v13/MTP_ySUJH_bn48VBG8sNSonF5uFdDttMLvmWuJdhhgs.ttf) format('truetype');
}
@font-face {
  font-family: 'Open Sans';
  font-style: italic;
  font-weight: 300;
  src: local('Open Sans Light Italic'), local('OpenSansLight-Italic'), url(https://fonts.gstatic.com/s/opensans/v13/PRmiXeptR36kaC0GEAetxrfB31yxOzP-czbf6AAKCVo.ttf) format('truetype');
}
@font-face {
  font-family: 'Open Sans';
  font-style: italic;
  font-weight: 400;
  src: local('Open Sans Italic'), local('OpenSans-Italic'), url(https://fonts.gstatic.com/s/opensans/v13/xjAJXh38I15wypJXxuGMBp0EAVxt0G0biEntp43Qt6E.ttf) format('truetype');
}
@font-face {
  font-family: 'Open Sans';
  font-style: italic;
  font-weight: 600;
  src: local('Open Sans Semibold Italic'), local('OpenSans-SemiboldItalic'), url(https://fonts.gstatic.com/s/opensans/v13/PRmiXeptR36kaC0GEAetxi8cqLH4MEiSE0ROcU-qHOA.ttf) format('truetype');
}
```

I count only 11 URLs there, and all of them come after `local()` entries. Even so, it strikes me as if we could easily extract the `.css` URL from all `.html` files in `$pkgdir/mingw64/share/doc/git-doc/` and `$pkgdir/mingw64/share/doc/git-doc/technical` (there is only one, we could hard-code it, even), download that as `fonts.css` next to the `index.html`, replace all of the `.css` URLs with local ones, and then download the `.ttf` files next to the `.css` and modify the `.css` to refer to the local `.ttf` files instead.

Something like

```sh
if test -n "$urls"
then
    case "$urls" in *\ *) die "We only support one unique Google Font CSS";; esac

    basedir="$pkgdir/${MINGW_PREFIX}/share/doc/git-doc/"

    # Download the CSS so it is available for offline use
    test -f "$basedir"/fonts.css ||
    curl -o "$basedir"/fonts.css $urls ||
    die "Could not download the Google Font CSS"

    # Download the TTFs so they are available for offline use
    (cd "$basedir &&
     for ttf in $(sed -n 's|.*url(\(https:[^)]*\).*|\1|p' <fonts.css)
     do
         curl -O $ttf ||
         die "Could not download $ttf"
     done)

    # Replace the remote TTF URLs with local ones
    sed -i 's|\(url(\)https://.*/\([^)]*\)|\1\2|' "$basedir"/fonts.css ||
    die "Could not replace the TTF URLs"

    # Replace the CSS URLs with the local one
    for html in "$basedir"/*.html
    do
        sed -i 's|$urls|fonts.css' $html
    done
    for html in "$basedir"/*/*.html
    do
        sed -i 's|$urls|../fonts.css' $html
    done
fi
```

Please test and fix as needed.
